const NEXT_ACTIONS = {
    EMAIL_VERIFICATION : "EMAIL_VERIFICATION",
    SET_PASSWORD : "SET_PASSWORD",
    PHONE_VERIFICATION : "PHONE_VERIFICATION",
    CREATE_PROFILE : "CREATE_PROFILE",
    UPLOAD_PROFILE_PHOTO: "UPLOAD_PROFILE_PHOTO" ,
    NONE:"NONE"
}
const MAIL_OPTIONS={
    VERIFY_EMAIL : "VERIFY_EMAIL",
    RESET_PASSWORD: "RESET_PASSWORD"
}
const TIER = {
    TIER1 : "TIER_1",
    TIER2 : "TIER_2",   
    TIER3 : "TIER_3",
}
const TASK_TYPE = {
    SIMPLE:'simple',
    GROUP:'group',
    COLLABORATIVE:'collaborative',
}
const USER_ROLE ={
    OWNER:'owner',
    MEMBER:'member',    
    ADMIN:'admin',
}

export {NEXT_ACTIONS , MAIL_OPTIONS, TIER, TASK_TYPE, USER_ROLE}