const NEXT_ACTIONS = {
    EMAIL_VERIFICATION : "EMAIL_VERIFICATION",
    SET_PASSWORD : "SET_PASSWORD",
    PHONE_VERIFICATION : "PHONE_VERIFICATION",
    CREATE_PROFILE : "CREATE_PROFILE",
    UPLOAD_PROFILE_PHOTO: "UPLOAD_PROFILE_PHOTO" ,
    NONE:"NONE"
}
const MAIL_OPTIONS={
    VERIFY_EMAIL : "VERIFY_EMAIL",
    RESET_PASSWORD: "RESET_PASSWORD"
}

export {NEXT_ACTIONS , MAIL_OPTIONS}