const NEXT_ACTIONS = {
    EMAIL_VERIFICATION : "EMAIL VERIFICATION",
    SET_PASSWORD : "SET_PASSWORD",
    PHONE_VERIFICATION : "PHONE_VERIFICATION",
    CREATE_PROFILE : "CREATE_PROFILE",
    UPLOAD_PROFILE_PHOTO: "UPLOAD_PROFILE_PHOTO" ,
    NONE:"NONE"
}

export {NEXT_ACTIONS}